on:
  push:
    branches:
      - main

name: Deploy stats containers
jobs:
  deploy-containers:
    name: deploy
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.FLUENTBITIO_HOST }}
          user: ${{ secrets.FLUENTBITIO_USERNAME }}
          key: ${{ secrets.FLUENTBITIO_SSHKEY }}
          command: |
            git -C fluent-bit-stats pull || git clone https://github.com/niedbalski/fluent-bit-stats.git
            cd fluent-bit-stats
            sed -i -e "s/\__GRAFANACLOUD_USERNAME__/${{ env.GRAFANACLOUD_USERNAME }}/g" config/prometheus.yml
            sed -i -e "s/\__GRAFANACLOUD_PASSWORD__/${{ env.GRAFANACLOUD_PASSWORD }}/g" config/prometheus.yml
            sudo make up
        env:
          GRAFANACLOUD_USERNAME: ${{ secrets.GRAFANACLOUD_USERNAME }}
          GRAFANACLOUD_PASSWORD: ${{ secrets.GRAFANACLOUD_PASSWORD }}